apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | b64enc | quote }}
  NEO4J_USER: {{ .Values.secrets.NEO4J_USER | b64enc | quote }}
  NEO4J_PASSWORD: {{ .Values.secrets.NEO4J_PASSWORD | b64enc | quote }}
  NEO4J_URI: {{ .Values.secrets.NEO4J_URI | b64enc | quote }}
  EMAIL_FROM: {{ .Values.secrets.EMAIL_FROM | b64enc | quote }}
  EMAIL_SMTP_HOST: {{ .Values.secrets.EMAIL_SMTP_HOST | b64enc | quote }}
  EMAIL_SMTP_LOGIN: {{ .Values.secrets.EMAIL_SMTP_LOGIN | b64enc | quote }}
  EMAIL_SMTP_PORT: {{ .Values.secrets.EMAIL_SMTP_PORT | toString | b64enc | quote }}
  EMAIL_SMTP_PW: {{ .Values.secrets.EMAIL_SMTP_PW | b64enc | quote }}
  AUTH_SECRET: {{ .Values.secrets.AUTH_SECRET | b64enc | quote }}
  AUTH_URL: {{ .Values.secrets.AUTH_URL | b64enc | quote }}